# Generated by Django 5.0.6 on 2024-05-27 23:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='Ano_Publicação',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='Código',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='Data_de_Entrada_do_Livro',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='Editora',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='Gênero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='Observações',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='Paginas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='Autor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='Nome_Do_Livro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
