# Generated by Django 5.0.6 on 2024-05-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_alter_cliente_data_de_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='Data_de_Contratação',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='Data_de_Nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='Email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='Endereço',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='Telefone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
