# Generated by Django 5.0.6 on 2024-05-28 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_funcionario_data_de_contratação_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Data_de_Devolução',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Data_de_Entrega_do_Livro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Data_de_Nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='CPF_Funcionario',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='Nome_Do_Funcionario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
